FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN corepack enable \
    && yarn set version stable \
    && yarn install \
    && rm -rf node_modules/
COPY . .
CMD ["yarn", "run", "devDocker"]
