version: '3.8'
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '8080:80'
        environment:
            - VITE_USER_NAME=Ralph-prod
